version: "3.9"

services:
  api:
    build: .
    container_name: drift_api
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/driftdb
      REDIS_URL: redis://redis:6379/0

  db:
    image: postgres:15
    container_name: drift_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: driftdb
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: drift_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  dbdata:
  redisdata:
